### ISSUE TITLE
primordials is not defined

### ISSUE THREAD

**Issue by ghost** [planetoftheweb/nextgen#1]
Following the course on Linkedin and following all steps carefully.
For 'Introduction - Using the exercise files' I have run NPM install then run the gulp command and the following shows up:
mark@mark nextgen % gulp
ReferenceError: primordials is not defined
    at fs.js:51:5
    at req_ (/Users/mark/Desktop/nextgen/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/Users/mark/Desktop/nextgen/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/Users/mark/Desktop/nextgen/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
mark@mark nextgen % 

Please let me know what happened.

Thanks.

**Comment by planetoftheweb** [comment]
I think it's an issue with the versions of Gulp and Node you have installed. Take a peek at this: https://stackoverflow.com/questions/55921442/how-to-fix-referenceerror-primordials-is-not-defined-in-node

**Comment by erdmann040** [comment]
Had the same problem and did not want to downgrade node or gulp. I have partially solved the problem by transforming the gulpfile.js file to a gulp 4 compatible form:
 
```
const { src, dest, series, watch } = require("gulp");

const webserver = require("gulp-webserver");
const postcss = require("gulp-postcss");
const cssnext = require("postcss-cssnext");
const { combine } = require("gulp-util");

const gutil = require("gulp-util");
const sourcemaps = require("gulp-sourcemaps");
const browserSync = require('browser-sync');

const source = "process/css/";
const destination = "builds/nextgen/";

function htmlTask(cb) {
  src(destination + "*.html");
  cb();
}

function cssTask(cb) {
  src(source + "style.css")
  .pipe(sourcemaps.init())
  .pipe(
      postcss([
        require("postcss-partial-import")({ prefix: "_", extension: ".css" }),
        cssnext(),
      ])
    )
    .on("error", gutil.log)
    .pipe(sourcemaps.write("."))
    .pipe(dest(destination + "css"));
  cb();
}

function watchTask(cb) {
  watch(source + "**/*.css").on('change', series(cssTask, browserSync.reload));
  watch(destination + "**/*.html").on('change', series(htmlTask, browserSync.reload));
  cb();
}

function serverTask(cb) {
  browserSync.init({
      server: {
          baseDir: destination 
      } 
  })
  cb();
}

exports.default = series(htmlTask, cssTask, serverTask, watchTask);

```
Now open a Terninal in your working directory and run 

`$ npm install --save-dev browser-sync`

Probably the code above can be improved, but this way I could run the default gulp command

`$ gulp `

The videos did not load in chrome, but in Firefox and the last script block at the end of the html page refuesed loading:

```
<script>//<![CDATA[
document.write('<script src="//' + (location.hostname || 'localhost') + ':35729/livereload.js?snipver=1"><\/script>')
//]]></script>
```

Im not sure if this is an issue that is related to my local LAMP environment. I am grateful for suggestions for improvement, but I think that I can follow the course this way.
